# generated by datamodel-codegen:
#   filename:  fight.json
#   timestamp: 2026-09-14T07:30:48+00:00

# datamodel-codegen --input fight.json --input-file-type json --output-model-type typing.TypedDict --target-python-version 3.12 --output model.py

from __future__ import annotations

from typing import Any, NotRequired, TypedDict


class Phase(TypedDict):
    id: int
    startTime: int


class Map(TypedDict):
    mapID: int
    mapName: str
    mapFile: str


class Fight(TypedDict):
    id: int
    boss: int
    start_time: int
    end_time: int
    name: str
    zoneID: int
    zoneName: str
    zoneCounter: int
    size: int
    difficulty: int
    kill: bool
    partial: int
    inProgress: bool
    standardComposition: bool
    hasEcho: bool
    hasTrustNPCs: bool
    combatTime: int
    bossPercentage: int
    fightPercentage: int
    lastPhaseAsAbsoluteIndex: int
    lastPhaseForPercentageDisplay: int
    lastCastGameId: NotRequired[int]
    lastCastTime: NotRequired[int]
    lastCastNumber: NotRequired[int]
    lastCastInProgress: NotRequired[bool]
    phases: list[Phase]
    maps: list[Map]


class Fight1(TypedDict):
    id: int


class Friendly(TypedDict):
    name: str
    id: int
    guid: int
    type: str
    server: NotRequired[str]
    icon: str
    fights: list[Fight1]


class Fight2(TypedDict):
    id: int
    instances: int
    groups: NotRequired[int]


class Enemy(TypedDict):
    name: str
    id: int
    guid: int
    type: str
    icon: str
    fights: list[Fight2]


class Fight3(TypedDict):
    id: int
    instances: int


class FriendlyPet(TypedDict):
    name: str
    id: int
    guid: int
    type: str
    icon: str
    petOwner: int
    fights: list[Fight3]


class Phase1(TypedDict):
    boss: int
    separatesWipes: bool
    phases: list[str]


class ExportedCharacter(TypedDict):
    id: int
    name: str
    server: str
    region: str


class FightsResponse(TypedDict):
    lang: str
    fights: list[Fight]
    friendlies: list[Friendly]
    enemies: list[Enemy]
    friendlyPets: list[FriendlyPet]
    enemyPets: list[Any]
    logVersion: int
    gameVersion: int
    phases: list[Phase1]
    title: str
    owner: str
    start: int
    end: int
    zone: int
    exportedCharacters: list[ExportedCharacter]
