# generated by datamodel-codegen:
#   filename:  summary.json
#   timestamp: 2026-09-14T07:43:39+00:00

# datamodel-codegen --input summary.json --input-file-type json --output-model-type typing.TypedDict --target-python-version 3.12 --output summary.py

from __future__ import annotations

from typing import Any, NotRequired, TypedDict


class Aura(TypedDict):
    source: int
    ability: int
    stacks: int
    icon: str
    name: str


class Ability(TypedDict):
    name: str
    guid: int
    type: int
    abilityIcon: str


class SourceResources(TypedDict):
    hitPoints: int
    maxHitPoints: int
    mp: int
    maxMP: int
    tp: int
    maxTP: int
    x: int
    y: int
    facing: int
    absorb: NotRequired[int]


class TargetResources(TypedDict):
    hitPoints: int
    maxHitPoints: int
    mp: int
    maxMP: int
    tp: int
    maxTP: int
    x: int
    y: int
    facing: int
    absorb: NotRequired[int]


class ExtraAbility(TypedDict):
    name: str
    guid: int
    type: int
    abilityIcon: str


class Target(TypedDict):
    name: str
    id: int
    guid: int
    type: str
    icon: str


class Source(TypedDict):
    name: str
    id: int
    guid: int
    type: str
    icon: str


class Event(TypedDict):
    timestamp: int
    type: str
    fight: int
    sourceID: NotRequired[int]
    gear: NotRequired[list[Any]]
    auras: NotRequired[list[Aura]]
    level: NotRequired[int]
    simulatedCrit: NotRequired[float]
    simulatedDirectHit: NotRequired[float]
    strength: NotRequired[int]
    dexterity: NotRequired[int]
    vitality: NotRequired[int]
    intelligence: NotRequired[int]
    mind: NotRequired[int]
    piety: NotRequired[int]
    attack: NotRequired[int]
    directHit: NotRequired[bool | int]
    criticalHit: NotRequired[int]
    attackMagicPotency: NotRequired[int]
    healMagicPotency: NotRequired[int]
    determination: NotRequired[int]
    skillSpeed: NotRequired[int]
    spellSpeed: NotRequired[int]
    tenacity: NotRequired[int]
    packetID: NotRequired[int]
    sourceIsFriendly: NotRequired[bool]
    targetID: NotRequired[int]
    targetInstance: NotRequired[int]
    targetIsFriendly: NotRequired[bool]
    ability: NotRequired[Ability]
    sourceResources: NotRequired[SourceResources]
    targetResources: NotRequired[TargetResources]
    hitType: NotRequired[int]
    amount: NotRequired[int]
    unmitigatedAmount: NotRequired[int]
    multiplier: NotRequired[float]
    unpaired: NotRequired[bool]
    extraAbility: NotRequired[ExtraAbility]
    duration: NotRequired[int]
    absorb: NotRequired[int]
    stack: NotRequired[int]
    extraInfo: NotRequired[int]
    melee: NotRequired[bool]
    value: NotRequired[int]
    bars: NotRequired[int]
    target: NotRequired[Target]
    bonusPercent: NotRequired[int]
    gaugeID: NotRequired[str]
    data1: NotRequired[str]
    data2: NotRequired[str]
    data3: NotRequired[str]
    data4: NotRequired[str]
    overheal: NotRequired[int]
    tick: NotRequired[bool]
    finalizedAmount: NotRequired[float]
    simulated: NotRequired[bool]
    expectedAmount: NotRequired[int]
    expectedCritRate: NotRequired[int]
    actorPotencyRatio: NotRequired[float]
    guessAmount: NotRequired[float]
    directHitPercentage: NotRequired[float]
    sourceInstance: NotRequired[int]
    absorbed: NotRequired[int]
    attackerID: NotRequired[int]
    attackerInstance: NotRequired[int]
    attackerIsFriendly: NotRequired[bool]
    blocked: NotRequired[int]
    mitigated: NotRequired[int]
    markerID: NotRequired[int]
    tetherID: NotRequired[int]
    isBuff: NotRequired[bool]
    source: NotRequired[Source]
    targetMarker: NotRequired[int]
    sourceMarker: NotRequired[int]
    targetable: NotRequired[int]


class SummaryResponse(TypedDict):
    events: list[Event]
    count: int
    nextPageTimestamp: NotRequired[int]
