# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, FFXIV!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  fetch:
    cmds:
      - bingkit-ffxiv scrap

  replace:
    cmds:
      - bingkit-ffxiv replace

  rsv:
    cmds:
      - bingkit-ffxiv rsv

  compare:
    cmds:
      - python compare.py -a

  lint:
    cmds:
      - pre-commit run -a
