# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, FFXIV!

env:
  PYTHONUTF8: "1"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  fetch:
    cmds:
      - bingkit-ffxiv scrap

  replace:
    cmds:
      - bingkit-ffxiv replace {{ .CLI_ARGS }}

  rsv:
    cmds:
      - bingkit-ffxiv rsv {{ .CLI_ARGS }}

  compare:
    cmds:
      - python compare.py -a

  lint:
    cmds:
      - prek run -a

  update:
    cmds:
      - prek auto-update
      - uv sync --upgrade --all-extras --all-groups
